name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo indir
      uses: actions/checkout@v3

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Paketleri kur
      run: |
        pip install buildozer
        pip install cython

    - name: APK build
      run: buildozer android debug

    - name: APK yükle
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk